= RHOSP18 - Provision Control Plane Services and Manage Data Plane Nodes
:navtitle: Home

Welcome to this quick course on _Provision Control Plane Services and Manage Data Plane Nodes in RHOSP18_. 

Red Hat OpenStack Services on OpenShift (RHOSO) is the next generation of Red Hat OpenStack Platform.
Click https://www.redhat.com/en/blog/red-hat-openstack-services-openshift-next-generation-red-hat-openstack-platform[here] for more information.

This course provides step-by-step instructions for deploying a Red Hat OpenStack Platform 18 cluster. 

The course includes a hands-on lab with a pre-deployed Red Hat OpenShift Container Platform (RHOCP) cluster. 
You will deploy Red Hat OpenStack control plane services on top of the RHOCP cluster. 
Additionally, this training covers the steps to provision a pre-deployed compute node that acts as the data plane of your RHOSP deployment. 
You will attach the pre-deployed compute node to the RHOSP18 control plane running on the OCP cluster.


== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Pedro Navarro Perez
* Fernando Lozano
* Ashish Shah

== Classroom Environment for Red Hat Associates

Continue using the https://demo.redhat.com/catalog?item=babylon-catalog-prod/equinix-metal.osp-on-ocp.prod&utm_source=webapp&utm_medium=share-link[Red Hat OpenStack Services on OpenShift Dev Preview Demo] lab for hands-on activity for this course.

* Click on `Order` button for `Red Hat OpenStack Services on OpenShift Dev Preview` catalog.
* Under `Activity` option select `Practice / Enablement`
* In the `Purpose` drop down box, select `Learning about the product`
* Leave all other options at default and click on `Order` button at bottom of the page.

NOTE: The catalog may take approximately 2 hours to get provisioned.

* On Demo Platform home page, click on `Services` option on left pane.
* Make sure the `Status` for your lab is displayed as `Running`
* Under the `Name` column, click on the link for your lab to see the lab access information.
* You should get important details about the lab access on your lab environment page, on `Info` tab.
* Login to the public IP of Host for your lab as `lab-user` with SSH password mentioned on Info page.
* On the hypervisor host, swtich from lab-user to root using `sudo -i` command.
* From `root@hypervisor` session run `ssh root@192.168.123.100` for login to bastion host using ssh key.
* Use `bastion` VM to proceed with the hands-on activity for the lab.

== Prerequisites

* RHEL system administration: RHCSA (RH124, RH134)
* Local container management on RHEL with podman (RH134).
* Basic operation of OpenStack Services on OpenShift: OSP-Operations-I-1 and OSP-Operations-I-2. [or equivalent courses from OSP 16/17]
* Basic administration of OpenStack Services on OpenShift: OSP-Administration-I-1, OSP-Administration-I-2, and OSP-Administration-I-3.
* Datacenter networking concepts: ISO model, VLANs, firewalls, and Internet protocols, including but not limited to ICMP, IP, and HTTP.

== Objectives

* Study traditional TripleO deployment verses deployment with OpenShift cluster.
* Learn the RHOSO deployment process overview.
* Identify the pre-requisites for RHOSO deployment.
* Deploy control plane services on the RHOCP cluster.
* Verify the functionality of control plane services.
* Deploy data plane node using RHOCP cluster.
* Verify functionality of data plane deployment.
* Discover RHOSP cluster function by deploying workload on it.
