= Install the OpenStack Operator

The OpenStack Operator functions as the main operator for Red Hat OpenStack 18 deployment. 
It acts as a "meta" operator, overseeing and configuring other operators for OpenStack by monitoring and managing their CustomResources (CRs). 
Moreover, installing this operator will automatically set up all necessary operator dependencies for installing and managing OpenStack.

Follow below steps for installation of Openstack Operator on RHOCP cluster.

. Clone the Files Repo (FIXME: avoid using custom repo and use the generic steps)
+
In the bastion terminal, clone the repo and change directory to the files that we will used later in the lab
+
[source,bash]
----
git clone https://github.com/pnavarro/showroom_osp-on-ocp-lb1374.git labrepo
cd labrepo/content/files
----

. Create required projects for the Openstack Operator installation.
+
The next installation step for the *OpenStack Operators* involves creating the *openstack-operators* and *openstack* projects for the RHOSO operators.
+
[source,bash]
----
oc new-project openstack-operators
oc new-project openstack
----

. Prepare the secret for installating the operators:
+
Login with your Red Hat account and create a secret:
+
[source,bash]
----
podman login --username "My-RH-username" --password "My-Password" registry.redhat.io --authfile auth.json
----
+
FIXME: use local repo

. Ensure that you observe the `Login Succeeded!` message in the output of the preceding command, then confirm the creation of the `auth.json` file.
[source,bash]
----
cat auth.json
----
. Create secret for the registry:
+
[source,bash]
----
oc create secret generic osp-operators-secret \
 -n openstack-operators \
 --from-file=.dockerconfigjson=auth.json \
 --type=kubernetes.io/dockerconfigjson
----

. Veify the secret is created:
+
[source,bash]
----
oc get secrets -n openstack-operators osp-operators-secret
----
+
.Sample Output
----
NAME                   TYPE                             DATA   AGE
osp-operators-secret   kubernetes.io/dockerconfigjson   1      10s
----

. Configure the **Catalog Source, OperatorGroup and Subscription** for the **OpenStack Operator** using your registry:
+
Create the new **CatalogSource, OperatorGroup, and Subscription** CRs in the **openstack** namespace from **files/openstack-operators.yaml**: You can cut and paste the referenced yamlfiles from the repo or you may wish to clone the repository onto the bastion which this guide will assume:
+
[source,bash]
----
oc apply -f osp-ng-openstack-operator.yaml
----

. Confirm that you have installed the Openstack Operator, *openstack-operator.openstack-operators*:
+
[source,bash]
----
oc get operators openstack-operator.openstack-operators
----

. Review the pods in the **openstack-operators** namespace:
+
[source,bash]
----
oc get pods -n openstack-operators
----

. If you run:
+
[source, bash]
----
oc get pods -n openstack-operators --sort-by=.metadata.creationTimestamp
----
+
You should see a list of completed pods and then the running openstack services pods.
It should look like:
+
.Sample Output
----
NAME                                                              READY   STATUS      RESTARTS   AGE
(...)
openstack-operator-index-89nv9                                    1/1     Running     0          7m30s

neutron-operator-controller-manager-5755996c4b-ctbf8              2/2     Running     0          7m19s
openstack-ansibleee-operator-controller-manager-6d7d77fc45pdtfj   2/2     Running     0          7m13s
openstack-operator-controller-manager-56fb74ccb7-r8lvn            2/2     Running     0          7m1s
dataplane-operator-controller-manager-6844bfd645-f2zvs            2/2     Running     0          7m1s
glance-operator-controller-manager-596b56cd5-rvfrm                2/2     Running     0          6m59s
swift-operator-controller-manager-df5fbbbc5-zscc5                 2/2     Running     0          6m49s
octavia-operator-controller-manager-6549bc8f-r6xbp                2/2     Running     0          6m42s
openstack-baremetal-operator-controller-manager-7cd655c4c7f5glm   2/2     Running     0          6m42s
barbican-operator-controller-manager-69b766c996-ldg4n             2/2     Running     0          6m28s
(...)
----
+
Wait to see all the `Running` pods in `READY` state.

. Configure Secure Access for OpenStack Services
+
NOTE:
We will be utilizing a preconfigured yaml file (`files/osp-ng-ctlplane-secret.yaml`) to create a base64 password for the heat the other services.
+
FIXME: avoid using preconfigured files

. Create the Secret:
+
[source,bash,role=execute]
----
oc create -f osp-ng-ctlplane-secret.yaml
----

. Verify the *Secret* was created:
+
[source,bash,role=execute]
----
oc describe secret osp-secret -n openstack
----
